[cursor.style]
  blinking = "On"
  shape = "Underline"

[font]
  [font.normal]
    family = "NotoSansM Nerd Font"
    style = 'Regular'
  [font.bold]
    family = "NotoSansM Nerd Font"
    style = 'Bold'
  [font.italic]
    family = "NotoSansM Nerd Font"
    style = 'Condensed Regular'

[window]
  dynamic_padding = true

[env]
  TERM = "xterm-256color"

[general]
  import = [
    "./alacritty_device.toml",
  ]
